In [128]:
import pandas as pd
import seaborn as sns
import numpy as np
import torch

In [129]:
class Feedforward(torch.nn.Module):
        def __init__(self, input_size, hidden_size, dropout):
            super(Feedforward, self).__init__()
            self.input_size = input_size
            self.hidden_size  = hidden_size
            self.fc1 = torch.nn.Linear(self.input_size, self.hidden_size)
            self.fc2 = torch.nn.Linear(self.hidden_size, self.hidden_size)
            self.fc3 = torch.nn.Linear(self.hidden_size, self.hidden_size)
            self.relu = torch.nn.ReLU()
            self.fc_out = torch.nn.Linear(self.hidden_size, 1)
            self.sigmoid = torch.nn.Sigmoid()
            self.dropout = torch.nn.Dropout(dropout)
            
        def forward(self, x):
            x = self.fc1(x)
            x = self.dropout(x)
            x = self.relu(x)
            x = self.fc2(x)
            x = self.dropout(x)
            x = self.relu(x)
            x = self.fc3(x)
            x = self.dropout(x)
            x = self.relu(x)
            output = self.fc_out(x)
            output = self.sigmoid(output)
            return output

In [130]:
data = pd.read_csv('/Users/nkerstingadxnet.com/Documents/Higgs/orig/atlas-higgs-challenge-2014-v2.csv')

In [131]:
data['Binary_Label'] = data['Label'].map({'s':1,'b':0})

In [76]:
data.head()

,EventId,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,...,PRI_jet_leading_phi,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_subleading_phi,PRI_jet_all_pt,Weight,Label,KaggleSet,KaggleWeight,Binary_Label
0,100000,138.470,51.655,97.827,27.980,0.91,124.711,2.666,3.064,41.928,...,0.444,46.062,1.24,-2.475,113.497,0.000814,s,t,0.002653,1
1,100001,160.937,68.768,103.235,48.146,-999.00,-999.000,-999.000,3.473,2.078,...,1.158,-999.000,-999.00,-999.000,46.226,0.681042,b,t,2.233584,0
2,100002,-999.000,162.172,125.953,35.635,-999.00,-999.000,-999.000,3.148,9.336,...,-2.028,-999.000,-999.00,-999.000,44.251,0.715742,b,t,2.347389,0
3,100003,143.905,81.417,80.943,0.414,-999.00,-999.000,-999.000,3.310,0.414,...,-999.000,-999.000,-999.00,-999.000,-0.000,1.660654,b,t,5.446378,0
4,100004,175.864,16.915,134.805,16.405,-999.00,-999.000,-999.000,3.891,16.405,...,-999.000,-999.000,-999.00,-999.000,0.000,1.904263,b,t,6.245333,0

In [133]:
# now replace all the '-999' values with NULL so we can properly handle them
nulled_data = data.replace(-999.0, np.nan)
train_data = nulled_data.loc[nulled_data['KaggleSet'] == 't'].copy(deep=True)
public_test_data = nulled_data.loc[nulled_data['KaggleSet'] == 'b'].copy(deep=True)
private_test_data = nulled_data.loc[nulled_data['KaggleSet'] == 'v'].copy(deep=True)

In [134]:
orig_train_data = train_data.copy(deep=True)
orig_public_test_data = public_test_data.copy(deep=True)
orig_private_test_data = private_test_data.copy(deep=True)


# now replace the null values with column averages
train_data.drop('EventId', axis=1, inplace=True)
train_data.drop('Label', axis=1, inplace=True)
train_data.drop('Binary_Label', axis=1, inplace=True)
train_data.drop('Weight', axis=1, inplace=True)
train_data.drop('KaggleWeight', axis=1, inplace=True)
train_data.drop('KaggleSet', axis=1, inplace=True)
for col in train_data:
    train_data[col].fillna(train_data[col].mean(), inplace=True)
#train_data.isnull().sum()


public_test_data.drop('EventId', axis=1, inplace=True)
public_test_data.drop('Label', axis=1, inplace=True)
public_test_data.drop('Binary_Label', axis=1, inplace=True)
public_test_data.drop('Weight', axis=1, inplace=True)
public_test_data.drop('KaggleWeight', axis=1, inplace=True)
public_test_data.drop('KaggleSet', axis=1, inplace=True)
for col in public_test_data:
    public_test_data[col].fillna(public_test_data[col].mean(), inplace=True)
#public_test_data.isnull().sum()


private_test_data.drop('EventId', axis=1, inplace=True)
private_test_data.drop('Label', axis=1, inplace=True)
private_test_data.drop('Binary_Label', axis=1, inplace=True)
private_test_data.drop('Weight', axis=1, inplace=True)
private_test_data.drop('KaggleWeight', axis=1, inplace=True)
private_test_data.drop('KaggleSet', axis=1, inplace=True)
for col in private_test_data:
    private_test_data[col].fillna(private_test_data[col].mean(), inplace=True)
#private_test_data.isnull().sum()

In [135]:
# now let's normalize
normed_train_data = (train_data - train_data.min())/(train_data.max() - train_data.min())

normed_public_test_data = (public_test_data - public_test_data.min())/(public_test_data.max() - public_test_data.min())

normed_private_test_data = (private_test_data - private_test_data.min())/(private_test_data.max() - private_test_data.min())

In [80]:
normed_train_data.head()

,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,DER_sum_pt,...,PRI_met_phi,PRI_met_sumet,PRI_jet_num,PRI_jet_leading_pt,PRI_jet_leading_eta,PRI_jet_leading_phi,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_subleading_phi,PRI_jet_all_pt
0,0.109407,0.074854,0.068128,0.009869,0.107021,0.022395,0.596501,0.521549,0.014789,0.083957,...,0.455920,0.123125,0.666667,0.034326,0.738942,0.570746,0.023229,0.637778,0.106143,0.069484
1,0.128398,0.099653,0.072155,0.016983,0.282693,0.072194,0.496154,0.596238,0.000733,0.043764,...,0.195099,0.075802,0.333333,0.014878,0.580573,0.684386,0.040031,0.498684,0.499748,0.028300
2,0.095365,0.235006,0.089071,0.012570,0.282693,0.072194,0.496154,0.536888,0.003293,0.083987,...,0.152132,0.123969,0.333333,0.013067,0.728162,0.177304,0.040031,0.498684,0.499748,0.027091
3,0.114001,0.117983,0.055557,0.000146,0.282693,0.072194,0.496154,0.566472,0.000146,0.016533,...,0.509548,0.036368,0.000000,0.050269,0.499636,0.498107,0.040031,0.498684,0.499748,-0.000000
4,0.141017,0.024512,0.095662,0.005787,0.282693,0.072194,0.496154,0.672571,0.005787,0.006576,...,0.361394,0.019823,0.000000,0.050269,0.499636,0.498107,0.040031,0.498684,0.499748,0.000000

In [29]:
normed_train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 250000 entries, 0 to 249999
Data columns (total 30 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   DER_mass_MMC                 250000 non-null  float64
 1   DER_mass_transverse_met_lep  250000 non-null  float64
 2   DER_mass_vis                 250000 non-null  float64
 3   DER_pt_h                     250000 non-null  float64
 4   DER_deltaeta_jet_jet         250000 non-null  float64
 5   DER_mass_jet_jet             250000 non-null  float64
 6   DER_prodeta_jet_jet          250000 non-null  float64
 7   DER_deltar_tau_lep           250000 non-null  float64
 8   DER_pt_tot                   250000 non-null  float64
 9   DER_sum_pt                   250000 non-null  float64
 10  DER_pt_ratio_lep_tau         250000 non-null  float64
 11  DER_met_phi_centrality       250000 non-null  float64
 12  DER_lep_eta_centrality       250000 non-null  float64
 13  PRI_tau_pt                   250000 non-null  float64
 14  PRI_tau_eta                  250000 non-null  float64
 15  PRI_tau_phi                  250000 non-null  float64
 16  PRI_lep_pt                   250000 non-null  float64
 17  PRI_lep_eta                  250000 non-null  float64
 18  PRI_lep_phi                  250000 non-null  float64
 19  PRI_met                      250000 non-null  float64
 20  PRI_met_phi                  250000 non-null  float64
 21  PRI_met_sumet                250000 non-null  float64
 22  PRI_jet_num                  250000 non-null  float64
 23  PRI_jet_leading_pt           250000 non-null  float64
 24  PRI_jet_leading_eta          250000 non-null  float64
 25  PRI_jet_leading_phi          250000 non-null  float64
 26  PRI_jet_subleading_pt        250000 non-null  float64
 27  PRI_jet_subleading_eta       250000 non-null  float64
 28  PRI_jet_subleading_phi       250000 non-null  float64
 29  PRI_jet_all_pt               250000 non-null  float64
dtypes: float64(30)
memory usage: 59.1 MB

In [136]:

#train_tensor_out = torch.tensor(orig_train_data['Binary_Label'].values)
#train_tensor = torch.tensor(normed_train_data.values)
train_input_data = []
for i in range(len(orig_train_data)):
   train_input_data.append([torch.tensor(normed_train_data.iloc[i], dtype=torch.float), torch.tensor(orig_train_data['Binary_Label'].iloc[i] , dtype=torch.float)])

In [137]:
valid_input_data = []
for i in range(len(orig_public_test_data)):
   valid_input_data.append([torch.tensor(normed_public_test_data.iloc[i], dtype=torch.float), torch.tensor(orig_public_test_data['Binary_Label'].iloc[i] , dtype=torch.float)])

In [138]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(train_input_data, batch_size=128, shuffle=True)
valid_dataloader = DataLoader(valid_input_data, batch_size=128, shuffle=True)

In [139]:
model = Feedforward(30, 600, 0.05)
criterion = torch.nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [37]:
torch.cuda.is_available()

False

In [140]:
import copy
import time

start_time = time.time()
epoch = 20
maxvalcount = 5
minval_loss = np.inf
valcount = maxvalcount
best_model = model
for epoch in range(epoch):
    print("EPOCH: ", epoch)
    model.train()
    for i,batch in enumerate(train_dataloader):
        inputs, output = batch
        optimizer.zero_grad()
        # Forward pass
        y_pred = model(inputs)
        # Compute Loss
        loss = criterion(y_pred.squeeze(), output)
        if i % 100 == 0:
            print('Batch {}: train loss: {}'.format(i, loss.item()))
        # Backward pass
        loss.backward()
        optimizer.step()
    # compute validation loss
    model.eval()
    with torch.set_grad_enabled(False):
        val_loss = 0
        for i,batch in enumerate(valid_dataloader):
            inputs, output = batch
            y_pred = model(inputs)
            y_pred = model(inputs)
            loss = criterion(y_pred.squeeze(), output)
            val_loss += loss
            if i % 100 == 0:
                print('Validation Batch {}: loss: {}'.format(i, loss.item()))
        avg_val_loss = val_loss / len(valid_dataloader)
        print(f"AVERAGE BATCH VAL LOSS = {avg_val_loss}")
    if avg_val_loss < minval_loss:
        minval_loss = avg_val_loss
        best_model = copy.deepcopy(model)
        valcount = maxvalcount
    else:
        valcount -= 1
    if valcount == 0:
        print(f"Validation Loss failed to decrease in {maxvalcount} epochs, exiting with best model")
        break
    
end_time = time.time()
print(f"Time elapsed in training: {end_time - start_time} seconds")

EPOCH:  0
Batch 0: train loss: 0.6893978118896484
Batch 100: train loss: 0.6534700393676758
Batch 200: train loss: 0.6424453854560852
Batch 300: train loss: 0.6695780158042908
Batch 400: train loss: 0.6515956521034241
Batch 500: train loss: 0.6388377547264099
Batch 600: train loss: 0.6270337700843811
Batch 700: train loss: 0.6635515689849854
Batch 800: train loss: 0.6014732122421265
Batch 900: train loss: 0.6275156140327454
Batch 1000: train loss: 0.6535892486572266
Batch 1100: train loss: 0.5935057401657104
Batch 1200: train loss: 0.5974753499031067
Batch 1300: train loss: 0.6020992398262024
Batch 1400: train loss: 0.6448183655738831
Batch 1500: train loss: 0.6010163426399231
Batch 1600: train loss: 0.5816610455513
Batch 1700: train loss: 0.5918084979057312
Batch 1800: train loss: 0.6079549193382263
Batch 1900: train loss: 0.5744369029998779
Validation Batch 0: loss: 0.5569058060646057
Validation Batch 100: loss: 0.6172940135002136
Validation Batch 200: loss: 0.577890157699585
Validation Batch 300: loss: 0.5957253575325012
Validation Batch 400: loss: 0.5995439291000366
Validation Batch 500: loss: 0.6098264455795288
Validation Batch 600: loss: 0.6067986488342285
Validation Batch 700: loss: 0.6121789813041687
AVERAGE BATCH VAL LOSS = 0.5974708199501038
EPOCH:  1
Batch 0: train loss: 0.5865467190742493
Batch 100: train loss: 0.5760411024093628
Batch 200: train loss: 0.5666532516479492
Batch 300: train loss: 0.5920436978340149
Batch 400: train loss: 0.5947837233543396
Batch 500: train loss: 0.5596571564674377
Batch 600: train loss: 0.6163333058357239
Batch 700: train loss: 0.5326962471008301
Batch 800: train loss: 0.6088936924934387
Batch 900: train loss: 0.5829750299453735
Batch 1000: train loss: 0.5670820474624634
Batch 1100: train loss: 0.5699688196182251
Batch 1200: train loss: 0.5543419122695923
Batch 1300: train loss: 0.5823556780815125
Batch 1400: train loss: 0.5618909597396851
Batch 1500: train loss: 0.6191913485527039
Batch 1600: train loss: 0.5584730505943298
Batch 1700: train loss: 0.5879756808280945
Batch 1800: train loss: 0.5911186337471008
Batch 1900: train loss: 0.5200380682945251
Validation Batch 0: loss: 0.5919986367225647
Validation Batch 100: loss: 0.5572316646575928
Validation Batch 200: loss: 0.5801716446876526
Validation Batch 300: loss: 0.5658877491950989
Validation Batch 400: loss: 0.5928196310997009
Validation Batch 500: loss: 0.539106011390686
Validation Batch 600: loss: 0.546203076839447
Validation Batch 700: loss: 0.5236095786094666
AVERAGE BATCH VAL LOSS = 0.577768087387085
EPOCH:  2
Batch 0: train loss: 0.5714219212532043
Batch 100: train loss: 0.5557351112365723
Batch 200: train loss: 0.5087510943412781
Batch 300: train loss: 0.6535999178886414
Batch 400: train loss: 0.5615935921669006
Batch 500: train loss: 0.5052404999732971
Batch 600: train loss: 0.5605646371841431
Batch 700: train loss: 0.5634240508079529
Batch 800: train loss: 0.5568156242370605
Batch 900: train loss: 0.5818732380867004
Batch 1000: train loss: 0.5671146512031555
Batch 1100: train loss: 0.5430760979652405
Batch 1200: train loss: 0.5761913061141968
Batch 1300: train loss: 0.5307492613792419
Batch 1400: train loss: 0.4973028302192688
Batch 1500: train loss: 0.5858572721481323
Batch 1600: train loss: 0.5796411633491516
Batch 1700: train loss: 0.5823375582695007
Batch 1800: train loss: 0.6645283102989197
Batch 1900: train loss: 0.5827812552452087
Validation Batch 0: loss: 0.594379723072052
Validation Batch 100: loss: 0.598713755607605
Validation Batch 200: loss: 0.5664377808570862
Validation Batch 300: loss: 0.5592159628868103
Validation Batch 400: loss: 0.552854061126709
Validation Batch 500: loss: 0.5780006647109985
Validation Batch 600: loss: 0.5911999344825745
Validation Batch 700: loss: 0.5190120935440063
AVERAGE BATCH VAL LOSS = 0.5640432834625244
EPOCH:  3
Batch 0: train loss: 0.6261702179908752
Batch 100: train loss: 0.598005473613739
Batch 200: train loss: 0.5878185033798218
Batch 300: train loss: 0.5356819033622742
Batch 400: train loss: 0.548148512840271
Batch 500: train loss: 0.5306673049926758
Batch 600: train loss: 0.5653752684593201
Batch 700: train loss: 0.5764702558517456
Batch 800: train loss: 0.5395311117172241
Batch 900: train loss: 0.5792213082313538
Batch 1000: train loss: 0.6015231013298035
Batch 1100: train loss: 0.552459180355072
Batch 1200: train loss: 0.505975604057312
Batch 1300: train loss: 0.4805765151977539
Batch 1400: train loss: 0.5314047932624817
Batch 1500: train loss: 0.536016583442688
Batch 1600: train loss: 0.5809081792831421
Batch 1700: train loss: 0.5608681440353394
Batch 1800: train loss: 0.4573063254356384
Batch 1900: train loss: 0.4735581874847412
Validation Batch 0: loss: 0.5901259183883667
Validation Batch 100: loss: 0.554767906665802
Validation Batch 200: loss: 0.5277725458145142
Validation Batch 300: loss: 0.5549410581588745
Validation Batch 400: loss: 0.5320174694061279
Validation Batch 500: loss: 0.5741395354270935
Validation Batch 600: loss: 0.574387788772583
Validation Batch 700: loss: 0.5814923644065857
AVERAGE BATCH VAL LOSS = 0.5571447610855103
EPOCH:  4
Batch 0: train loss: 0.49293258786201477
Batch 100: train loss: 0.5605936646461487
Batch 200: train loss: 0.5268474221229553
Batch 300: train loss: 0.5391499996185303
Batch 400: train loss: 0.5371376872062683
Batch 500: train loss: 0.4973706901073456
Batch 600: train loss: 0.5771080255508423
Batch 700: train loss: 0.5329350233078003
Batch 800: train loss: 0.563461422920227
Batch 900: train loss: 0.5608462691307068
Batch 1000: train loss: 0.5045912265777588
Batch 1100: train loss: 0.5237851142883301
Batch 1200: train loss: 0.5222482085227966
Batch 1300: train loss: 0.5228743553161621
Batch 1400: train loss: 0.5203501582145691
Batch 1500: train loss: 0.5538109540939331
Batch 1600: train loss: 0.5006380081176758
Batch 1700: train loss: 0.5041227340698242
Batch 1800: train loss: 0.5261064767837524
Batch 1900: train loss: 0.5188775658607483
Validation Batch 0: loss: 0.5718687176704407
Validation Batch 100: loss: 0.5478971600532532
Validation Batch 200: loss: 0.5580648183822632
Validation Batch 300: loss: 0.5347337126731873
Validation Batch 400: loss: 0.5618909001350403
Validation Batch 500: loss: 0.5753846764564514
Validation Batch 600: loss: 0.5330389142036438
Validation Batch 700: loss: 0.5593897700309753
AVERAGE BATCH VAL LOSS = 0.5357829928398132
EPOCH:  5
Batch 0: train loss: 0.5415416359901428
Batch 100: train loss: 0.5559614300727844
Batch 200: train loss: 0.49793076515197754
Batch 300: train loss: 0.5276281833648682
Batch 400: train loss: 0.5164257287979126
Batch 500: train loss: 0.5224452018737793
Batch 600: train loss: 0.5050755739212036
Batch 700: train loss: 0.5643690228462219
Batch 800: train loss: 0.5144819617271423
Batch 900: train loss: 0.5271013379096985
Batch 1000: train loss: 0.5248780846595764
Batch 1100: train loss: 0.5355352163314819
Batch 1200: train loss: 0.47694137692451477
Batch 1300: train loss: 0.4809355139732361
Batch 1400: train loss: 0.4155455529689789
Batch 1500: train loss: 0.5318270921707153
Batch 1600: train loss: 0.5074724555015564
Batch 1700: train loss: 0.4834539592266083
Batch 1800: train loss: 0.4855118989944458
Batch 1900: train loss: 0.48301929235458374
Validation Batch 0: loss: 0.5383164286613464
Validation Batch 100: loss: 0.6169833540916443
Validation Batch 200: loss: 0.4980427324771881
Validation Batch 300: loss: 0.4910360276699066
Validation Batch 400: loss: 0.5669704675674438
Validation Batch 500: loss: 0.5218085050582886
Validation Batch 600: loss: 0.5304362773895264
Validation Batch 700: loss: 0.48858338594436646
AVERAGE BATCH VAL LOSS = 0.5199863910675049
EPOCH:  6
Batch 0: train loss: 0.48618489503860474
Batch 100: train loss: 0.48805859684944153
Batch 200: train loss: 0.4823710024356842
Batch 300: train loss: 0.496721476316452
Batch 400: train loss: 0.49372249841690063
Batch 500: train loss: 0.6070144176483154
Batch 600: train loss: 0.4985789358615875
Batch 700: train loss: 0.5237107276916504
Batch 800: train loss: 0.49501171708106995
Batch 900: train loss: 0.4595777988433838
Batch 1000: train loss: 0.5097792744636536
Batch 1100: train loss: 0.4440678358078003
Batch 1200: train loss: 0.5057026147842407

Batch 1300: train loss: 0.5257290601730347
Batch 1400: train loss: 0.49645230174064636
Batch 1500: train loss: 0.5808191299438477
Batch 1600: train loss: 0.528102695941925
Batch 1700: train loss: 0.49206873774528503
Batch 1800: train loss: 0.4660507142543793
Batch 1900: train loss: 0.5695800185203552
Validation Batch 0: loss: 0.597465991973877
Validation Batch 100: loss: 0.6357811689376831
Validation Batch 200: loss: 0.5783658623695374
Validation Batch 300: loss: 0.5292744040489197
Validation Batch 400: loss: 0.6580393314361572
Validation Batch 500: loss: 0.5828341245651245
Validation Batch 600: loss: 0.5687484741210938
Validation Batch 700: loss: 0.6185050010681152
AVERAGE BATCH VAL LOSS = 0.5973839163780212
EPOCH:  7
Batch 0: train loss: 0.49329739809036255
Batch 100: train loss: 0.5430585145950317
Batch 200: train loss: 0.5103341341018677
Batch 300: train loss: 0.4258919358253479
Batch 400: train loss: 0.5018779635429382
Batch 500: train loss: 0.4492100179195404
Batch 600: train loss: 0.5209134221076965
Batch 700: train loss: 0.49303287267684937
Batch 800: train loss: 0.4892148971557617
Batch 900: train loss: 0.49931514263153076
Batch 1000: train loss: 0.43742215633392334
Batch 1100: train loss: 0.5071415901184082
Batch 1200: train loss: 0.45068594813346863
Batch 1300: train loss: 0.5339640974998474
Batch 1400: train loss: 0.5361099243164062
Batch 1500: train loss: 0.47334715723991394
Batch 1600: train loss: 0.4920337200164795
Batch 1700: train loss: 0.4942796230316162
Batch 1800: train loss: 0.49495798349380493
Batch 1900: train loss: 0.474445104598999
Validation Batch 0: loss: 0.5194742679595947
Validation Batch 100: loss: 0.5498131513595581
Validation Batch 200: loss: 0.5435258746147156
Validation Batch 300: loss: 0.583250880241394
Validation Batch 400: loss: 0.5572726130485535
Validation Batch 500: loss: 0.5416014790534973
Validation Batch 600: loss: 0.6264550089836121
Validation Batch 700: loss: 0.5078945755958557
AVERAGE BATCH VAL LOSS = 0.5390920042991638
EPOCH:  8
Batch 0: train loss: 0.5908775925636292
Batch 100: train loss: 0.48301512002944946
Batch 200: train loss: 0.4841145873069763
Batch 300: train loss: 0.4661811292171478
Batch 400: train loss: 0.41341811418533325
Batch 500: train loss: 0.4042716324329376
Batch 600: train loss: 0.4598710834980011
Batch 700: train loss: 0.4765329360961914
Batch 800: train loss: 0.5016549825668335
Batch 900: train loss: 0.48502135276794434
Batch 1000: train loss: 0.4861324727535248
Batch 1100: train loss: 0.38375192880630493
Batch 1200: train loss: 0.5055994987487793
Batch 1300: train loss: 0.44152000546455383
Batch 1400: train loss: 0.467893123626709
Batch 1500: train loss: 0.45578116178512573
Batch 1600: train loss: 0.5223107933998108
Batch 1700: train loss: 0.44456061720848083
Batch 1800: train loss: 0.4089762568473816
Batch 1900: train loss: 0.44859784841537476
Validation Batch 0: loss: 0.5449835062026978
Validation Batch 100: loss: 0.4897734820842743
Validation Batch 200: loss: 0.6214948892593384
Validation Batch 300: loss: 0.6136310696601868
Validation Batch 400: loss: 0.580223023891449
Validation Batch 500: loss: 0.611196756362915
Validation Batch 600: loss: 0.5731357932090759
Validation Batch 700: loss: 0.5135515332221985
AVERAGE BATCH VAL LOSS = 0.5666213035583496
EPOCH:  9
Batch 0: train loss: 0.47592172026634216
Batch 100: train loss: 0.45654532313346863
Batch 200: train loss: 0.38128921389579773
Batch 300: train loss: 0.4488584101200104
Batch 400: train loss: 0.4935259222984314
Batch 500: train loss: 0.39122676849365234
Batch 600: train loss: 0.4729245603084564
Batch 700: train loss: 0.4305901527404785
Batch 800: train loss: 0.519920289516449
Batch 900: train loss: 0.44788858294487
Batch 1000: train loss: 0.4363669455051422
Batch 1100: train loss: 0.5054042339324951
Batch 1200: train loss: 0.5042790174484253
Batch 1300: train loss: 0.47000551223754883
Batch 1400: train loss: 0.47053131461143494
Batch 1500: train loss: 0.4759311079978943
Batch 1600: train loss: 0.4607950747013092
Batch 1700: train loss: 0.41523462533950806
Batch 1800: train loss: 0.4906976521015167
Batch 1900: train loss: 0.46325987577438354
Validation Batch 0: loss: 0.6134192943572998
Validation Batch 100: loss: 0.5347810387611389
Validation Batch 200: loss: 0.49237531423568726
Validation Batch 300: loss: 0.6749967336654663
Validation Batch 400: loss: 0.5366184115409851
Validation Batch 500: loss: 0.5519797205924988
Validation Batch 600: loss: 0.6790860891342163
Validation Batch 700: loss: 0.6583208441734314
AVERAGE BATCH VAL LOSS = 0.6283890008926392
EPOCH:  10
Batch 0: train loss: 0.5775030851364136
Batch 100: train loss: 0.49719974398612976
Batch 200: train loss: 0.4206138849258423
Batch 300: train loss: 0.4506770372390747
Batch 400: train loss: 0.4083516299724579
Batch 500: train loss: 0.5303581953048706
Batch 600: train loss: 0.4363866150379181
Batch 700: train loss: 0.5193422436714172
Batch 800: train loss: 0.521395206451416
Batch 900: train loss: 0.47391942143440247
Batch 1000: train loss: 0.49063292145729065
Batch 1100: train loss: 0.48450663685798645
Batch 1200: train loss: 0.39932432770729065
Batch 1300: train loss: 0.4644090533256531
Batch 1400: train loss: 0.4145183265209198
Batch 1500: train loss: 0.4356983006000519
Batch 1600: train loss: 0.40607425570487976
Batch 1700: train loss: 0.4509545862674713
Batch 1800: train loss: 0.4287598729133606
Batch 1900: train loss: 0.5352314710617065
Validation Batch 0: loss: 0.579352855682373
Validation Batch 100: loss: 0.6071515083312988
Validation Batch 200: loss: 0.613426685333252
Validation Batch 300: loss: 0.6040602922439575
Validation Batch 400: loss: 0.6511436104774475
Validation Batch 500: loss: 0.6143403649330139
Validation Batch 600: loss: 0.5531874299049377
Validation Batch 700: loss: 0.5343687534332275
AVERAGE BATCH VAL LOSS = 0.6163049340248108
Validation Loss failed to decrease in 5 epochs, exiting with best model
Time elapsed in training: 367.64980721473694 seconds

In [141]:
torch.save(best_model, '/Users/nkerstingadxnet.com/Documents/Higgs/output/mlp.600.pt')

In [142]:
best_model.eval()
y_pred = model(torch.tensor(normed_train_data.values, dtype=torch.float)).tolist()

In [121]:
y_pred

[[0.34261271357536316],
 [0.238296240568161],
 [0.07937367260456085],
 [0.08683201670646667],
 [0.16980604827404022],
 [0.22682584822177887],
 [0.5301306843757629],
 [0.8640022873878479],
 [0.1804657280445099],
 [0.7638903260231018],
 [0.12828156352043152],
 [0.6050633788108826],
 [0.6843826174736023],
 [0.20764213800430298],
 [0.011167837306857109],
 [0.5071235299110413],
 [0.6827844381332397],
 [0.5607870221138],
 [0.06456384807825089],
 [0.03918009623885155],
 [0.03373033553361893],
 [0.28969743847846985],
 [0.2322460412979126],
 [0.7238510251045227],
 [0.27337446808815],
 [0.42022714018821716],
 [0.788186252117157],
 [0.9128872752189636],
 [0.5215741395950317],
 [0.8364686965942383],
 [0.03179359808564186],
 [0.6772437691688538],
 [0.943113386631012],
 [0.7536647319793701],
 [0.444439560174942],
 [0.34249886870384216],
 [0.8707319498062134],
 [0.45973116159439087],
 [0.095066599547863],
 [0.6292946934700012],
 [0.44185730814933777],
 [0.12578827142715454],
 [0.8793133497238159],
 [0.20911014080047607],
 [0.2526666820049286],
 [0.01677064597606659],
 [0.8741018772125244],
 [0.5474327802658081],
 [0.7796915769577026],
 [0.797180712223053],
 [0.032189205288887024],
 [0.882780909538269],
 [0.03698815032839775],
 [0.1306491494178772],
 [0.01689171977341175],
 [0.03401464223861694],
 [0.15471668541431427],
 [0.5490791201591492],
 [0.4520159959793091],
 [0.036504097282886505],
 [0.46171948313713074],
 [0.20576801896095276],
 [0.4449896216392517],
 [0.1866140216588974],
 [0.37784063816070557],
 [0.07366009801626205],
 [0.6133551597595215],
 [0.13699521124362946],
 [0.515354335308075],
 [0.127834290266037],
 [0.4001925587654114],
 [0.32501131296157837],
 [0.1430400013923645],
 [0.5610577464103699],
 [0.06287506967782974],
 [0.528184175491333],
 [0.10317476838827133],
 [0.06462748348712921],
 [0.898070216178894],
 [0.8226377964019775],
 [0.17548897862434387],
 [0.15406093001365662],
 [0.280904084444046],
 [0.696961522102356],
 [0.24525122344493866],
 [0.020975982770323753],
 [0.06863319128751755],
 [0.1431974172592163],
 [0.0842982605099678],
 [0.32646530866622925],
 [0.20854021608829498],
 [0.3226352334022522],
 [0.1691080778837204],
 [0.922584593296051],
 [0.6838798522949219],
 [0.08727040141820908],
 [0.3150470554828644],
 [0.3250730633735657],
 [0.10936536639928818],
 [0.2734498977661133],
 [0.3730434477329254],
 [0.7159892916679382],
 [0.07086297124624252],
 [0.819749116897583],
 [0.32403942942619324],
 [0.12830805778503418],
 [0.8946850299835205],
 [0.8273455500602722],
 [0.10560768842697144],
 [0.13004018366336823],
 [0.8286724090576172],
 [0.3239472806453705],
 [0.08168498426675797],
 [0.26414185762405396],
 [0.04846218600869179],
 [0.6575800180435181],
 [0.03474042937159538],
 [0.031891487538814545],
 [0.3228289783000946],
 [0.9055038094520569],
 [0.1964147388935089],
 [0.5927305817604065],
 [0.04446568712592125],
 [0.042100533843040466],
 [0.07615652680397034],
 [0.9291948080062866],
 [0.0387265644967556],
 [0.357075959444046],
 [0.4989766478538513],
 [0.019422566518187523],
 [0.026779670268297195],
 [0.07371819764375687],
 [0.12365040928125381],
 [0.5369823575019836],
 [0.07141163945198059],
 [0.9703404903411865],
 [0.1926521509885788],
 [0.05056822672486305],
 [0.019235167652368546],
 [0.3306574523448944],
 [0.08136798441410065],
 [0.07156408578157425],
 [0.567127525806427],
 [0.13739439845085144],
 [0.6705948114395142],
 [0.056211918592453],
 [0.03256790712475777],
 [0.6817596554756165],
 [0.6805300116539001],
 [0.8296383619308472],
 [0.7850441336631775],
 [0.5207031965255737],
 [0.06556518375873566],
 [0.29025086760520935],
 [0.4526808559894562],
 [0.14691062271595],
 [0.3619394302368164],
 [0.15996338427066803],
 [0.32355138659477234],
 [0.1401979923248291],
 [0.06646480411291122],
 [0.2832721471786499],
 [0.12396775186061859],
 [0.025046726688742638],
 [0.7309073209762573],
 [0.06603611260652542],
 [0.7105780839920044],
 [0.8056648373603821],
 [0.06542706489562988],
 [0.47815942764282227],
 [0.09686579555273056],
 [0.038158316165208817],
 [0.06463401019573212],
 [0.024688389152288437],
 [0.21722330152988434],
 [0.05807996168732643],
 [0.17869816720485687],
 [0.10084990411996841],
 [0.05372156202793121],
 [0.5832039713859558],
 [0.009135373868048191],
 [0.23342952132225037],
 [0.8260054588317871],
 [0.5655682682991028],
 [0.06550046056509018],
 [0.01787201687693596],
 [0.08522626757621765],
 [0.8303703665733337],
 [0.15278613567352295],
 [0.03381123021245003],
 [0.5484501719474792],
 [0.5315877795219421],
 [0.35098475217819214],
 [0.010478105396032333],
 [0.032124485820531845],
 [0.013142473064363003],
 [0.05694838985800743],
 [0.13361114263534546],
 [0.17257028818130493],
 [0.7371549606323242],
 [0.5971156358718872],
 [0.7813048958778381],
 [0.8322674036026001],
 [0.043039362877607346],
 [0.9019736051559448],
 [0.6404611468315125],
 [0.5473955273628235],
 [0.019204849377274513],
 [0.5344604253768921],
 [0.15855620801448822],
 [0.5502346754074097],
 [0.1913759559392929],
 [0.5243831872940063],
 [0.03959653154015541],
 [0.22780516743659973],
 [0.19611488282680511],
 [0.04952053353190422],
 [0.09191930294036865],
 [0.05873102694749832],
 [0.9459086060523987],
 [0.8680968880653381],
 [0.7385453581809998],
 [0.5935553312301636],
 [0.12676122784614563],
 [0.859978437423706],
 [0.0016563375247642398],
 [0.3799148201942444],
 [0.027098264545202255],
 [0.39064034819602966],
 [0.1249132752418518],
 [0.12062832713127136],
 [0.39130699634552],
 [0.22690095007419586],
 [0.14659981429576874],
 [0.24907255172729492],
 [0.8511015772819519],
 [0.6238798499107361],
 [0.6552826166152954],
 [0.908740222454071],
 [0.683607816696167],
 [0.14654482901096344],
 [0.0559743195772171],
 [0.0298997201025486],
 [0.17657779157161713],
 [0.5292149186134338],
 [0.9518288969993591],
 [0.8315959572792053],
 [0.6206362843513489],
 [0.4134950041770935],
 [0.24254634976387024],
 [0.6178259253501892],
 [0.5771353244781494],
 [0.526892364025116],
 [0.08215562254190445],
 [0.03074709326028824],
 [0.5679886341094971],
 [0.1263849139213562],
 [0.8556091785430908],
 [0.629631757736206],
 [0.2332688719034195],
 [0.2367091029882431],
 [0.6080372929573059],
 [0.6965869665145874],
 [0.0450751893222332],
 [0.8321055173873901],
 [0.34416496753692627],
 [0.20821735262870789],
 [0.2526569366455078],
 [0.011543619446456432],
 [0.7523829340934753],
 [0.3059735596179962],
 [0.5655274391174316],
 [0.054980818182229996],
 [0.6871472597122192],
 [0.07265416532754898],
 [0.036574121564626694],
 [0.07926659286022186],
 [0.7420541644096375],
 [0.11360185593366623],
 [0.5898528099060059],
 [0.5417675375938416],
 [0.6556171178817749],
 [0.29645052552223206],
 [0.3170134127140045],
 [0.5505532622337341],
 [0.6924012899398804],
 [0.6377379298210144],
 [0.010332370176911354],
 [0.18434292078018188],
 [0.04003782942891121],
 [0.09372434765100479],
 [0.049258142709732056],
 [0.08442308753728867],
 [0.016462786123156548],
 [0.3581934869289398],
 [0.7822514772415161],
 [0.945727527141571],
 [0.3588844835758209],
 [0.2852596938610077],
 [0.04308779910206795],
 [0.2838970124721527],
 [0.19896668195724487],
 [0.6013434529304504],
 [0.745849072933197],
 [0.3567025363445282],
 [0.01593019813299179],
 [0.9157325029373169],
 [0.4933330714702606],
 [0.7567185759544373],
 [0.35068345069885254],
 [0.3395150601863861],
 [0.19326183199882507],
 [0.4579603374004364],
 [0.4445662796497345],
 [0.3461660146713257],
 [0.5550927519798279],
 [0.6532519459724426],
 [0.2551708519458771],
 [0.4974125623703003],
 [0.7126954197883606],
 [0.44140905141830444],
 [0.6152916550636292],
 [0.9541594386100769],
 [0.04881921410560608],
 [0.6457660794258118],
 [0.7905063033103943],
 [0.4044700264930725],
 [0.19243882596492767],
 [0.4242177903652191],
 [0.567355751991272],
 [0.028449419885873795],
 [0.02810288593173027],
 [0.6522433757781982],
 [0.4359142780303955],
 [0.6173554062843323],
 [0.8311527967453003],
 [0.17961768805980682],
 [0.10265441238880157],
 [0.5942794680595398],
 [0.4971352815628052],
 [0.7301353216171265],
 [0.8907400965690613],
 [0.08649186789989471],
 [0.2513529062271118],
 [0.3899427652359009],
 [0.6080835461616516],
 [0.06380709260702133],
 [0.16452118754386902],
 [0.15779076516628265],
 [0.11897975951433182],
 [0.0763775184750557],
 [0.36721310019493103],
 [0.09771407395601273],
 [0.6084348559379578],
 [0.8980464339256287],
 [0.25146180391311646],
 [0.03151669725775719],
 [0.354819655418396],
 [0.013486248441040516],
 [0.2653754949569702],
 [0.013017965480685234],
 [0.1425841599702835],
 [0.04372323676943779],
 [0.0306955948472023],
 [0.6544320583343506],
 [0.9358612298965454],
 [0.408203661441803],
 [0.7908190488815308],
 [0.09466278553009033],
 [0.0433022640645504],
 [0.24204562604427338],
 [0.6870134472846985],
 [0.25228604674339294],
 [0.0951320007443428],
 [0.2562277019023895],
 [0.9078231453895569],
 [0.7422478795051575],
 [0.6043469309806824],
 [0.7974379062652588],
 [0.05783812329173088],
 [0.03198269009590149],
 [0.09378785640001297],
 [0.047235775738954544],
 [0.6946058869361877],
 [0.07839132845401764],
 [0.1268191635608673],
 [0.09496363252401352],
 [0.33549734950065613],
 [0.5485469102859497],
 [0.031775299459695816],
 [0.27070942521095276],
 [0.021773146465420723],
 [0.23251061141490936],
 [0.6370157599449158],
 [0.30616387724876404],
 [0.9179043769836426],
 [0.013936523348093033],
 [0.17430643737316132],
 [0.8546718955039978],
 [0.9644913077354431],
 [0.5245579481124878],
 [0.40752220153808594],
 [0.7591819167137146],
 [0.1038416251540184],
 [0.01264198962599039],
 [0.2656955420970917],
 [0.3109723925590515],
 [0.0745702013373375],
 [0.3524569571018219],
 [0.06676781922578812],
 [0.7492822408676147],
 [0.4552302062511444],
 [0.23626144230365753],
 [0.6119006872177124],
 [0.920397937297821],
 [0.027265628799796104],
 [0.05659230053424835],
 [0.028875213116407394],
 [0.5858516097068787],
 [0.3953551650047302],
 [0.5375109910964966],
 [0.5742684602737427],
 [0.8421018123626709],
 [0.6136689782142639],
 [0.21003466844558716],
 [0.0881931483745575],
 [0.3526074290275574],
 [0.1783825159072876],
 [0.8668026328086853],
 [0.1571771800518036],
 [0.1929844468832016],
 [0.7126466631889343],
 [0.24537494778633118],
 [0.09421899169683456],
 [0.05067010968923569],
 [0.4049794375896454],
 [0.9156006574630737],
 [0.5237438082695007],
 [0.010961898602545261],
 [0.34955987334251404],
 [0.012021846137940884],
 [0.03515288233757019],
 [0.7932154536247253],
 [0.7170114517211914],
 [0.29447516798973083],
 [0.0165856946259737],
 [0.017945777624845505],
 [0.11905281245708466],
 [0.26087427139282227],
 [0.08154352009296417],
 [0.8621498942375183],
 [0.22876212000846863],
 [0.01499629020690918],
 [0.12119351327419281],
 [0.5111090540885925],
 [0.448323518037796],
 [0.15778253972530365],
 [0.2577347755432129],
 [0.16510078310966492],
 [0.20815780758857727],
 [0.2745340168476105],
 [0.1841537356376648],
 [0.5266356468200684],
 [0.144900843501091],
 [0.5847406983375549],
 [0.37790271639823914],
 [0.06493382900953293],
 [0.25018733739852905],
 [0.9496040940284729],
 [0.38805800676345825],
 [0.770810067653656],
 [0.27933475375175476],
 [0.7212817668914795],
 [0.3933660089969635],
 [0.5966546535491943],
 [0.4878985285758972],
 [0.04310721158981323],
 [0.17769166827201843],
 [0.730279803276062],
 [0.5218521952629089],
 [0.019313810393214226],
 [0.74012291431427],
 [0.4638398289680481],
 [0.6304428577423096],
 [0.2179112732410431],
 [0.045485686510801315],
 [0.0300028994679451],
 [0.45916518568992615],
 [0.28067547082901],
 [0.835145890712738],
 [0.04123793542385101],
 [0.28717926144599915],
 [0.1517535150051117],
 [0.16960813105106354],
 [0.11903602629899979],
 [0.4279644787311554],
 [0.36383041739463806],
 [0.8072562217712402],
 [0.9110799431800842],
 [0.3050882816314697],
 [0.15631815791130066],
 [0.674927294254303],
 [0.8569293022155762],
 [0.05889471620321274],
 [0.5679758787155151],
 [0.19081778824329376],
 [0.4903380870819092],
 [0.7965327501296997],
 [0.4151214063167572],
 [0.3108576536178589],
 [0.529927670955658],
 [0.552173912525177],
 [0.934368908405304],
 [0.016322577372193336],
 [0.8485007882118225],
 [0.20375974476337433],
 [0.10260158777236938],
 [0.13486236333847046],
 [0.06858857721090317],
 [0.7062398791313171],
 [0.8204056024551392],
 [0.6292420029640198],
 [0.8051815629005432],
 [0.2885153293609619],
 [0.14093245565891266],
 [0.7136523127555847],
 [0.11797527223825455],
 [0.16404712200164795],
 [0.834974467754364],
 [0.9414857625961304],
 [0.5624508261680603],
 [0.3228923976421356],
 [0.7338111996650696],
 [0.40905752778053284],
 [0.8370671272277832],
 [0.5635687708854675],
 [0.024940764531493187],
 [0.5540178418159485],
 [0.05856650695204735],
 [0.5107515454292297],
 [0.3683607280254364],
 [0.4421108067035675],
 [0.06286967545747757],
 [0.16419099271297455],
 [0.009449617005884647],
 [0.503925085067749],
 [0.11879129707813263],
 [0.12260272353887558],
 [0.027991998940706253],
 [0.47058337926864624],
 [0.07060517370700836],
 [0.0761631578207016],
 [0.5836377739906311],
 [0.18823422491550446],
 [0.877336323261261],
 [0.3653103709220886],
 [0.6386677026748657],
 [0.8200010061264038],
 [0.1982853263616562],
 [0.22093266248703003],
 [0.2790343761444092],
 [0.04018701985478401],
 [0.041933100670576096],
 [0.3944602310657501],
 [0.631797194480896],
 [0.042784616351127625],
 [0.8525729775428772],
 [0.20184141397476196],
 [0.20824742317199707],
 [0.17017897963523865],
 [0.04668384790420532],
 [0.5515238046646118],
 [0.8067095279693604],
 [0.2758049964904785],
 [0.622867226600647],
 [0.3414188027381897],
 [0.09884989261627197],
 [0.05837259441614151],
 [0.05543849617242813],
 [0.4322132468223572],
 [0.8122981786727905],
 [0.6487144231796265],
 [0.6741601228713989],
 [0.054364755749702454],
 [0.31734365224838257],
 [0.6857150197029114],
 [0.8206186890602112],
 [0.5124978423118591],
 [0.18143528699874878],
 [0.7558121681213379],
 [0.5326438546180725],
 [0.4059455096721649],
 [0.3334934711456299],
 [0.07355146110057831],
 [0.2715805768966675],
 [0.3796335756778717],
 [0.027292491868138313],
 [0.7577999830245972],
 [0.5432547330856323],
 [0.44109541177749634],
 [0.3783162832260132],
 [0.30288705229759216],
 [0.010288815945386887],
 [0.1673043966293335],
 [0.042321451008319855],
 [0.08011172711849213],
 [0.6497467756271362],
 [0.01401576679199934],
 [0.042403269559144974],
 [0.03261621296405792],
 [0.2940770387649536],
 [0.6354332566261292],
 [0.4765413999557495],
 [0.05491413548588753],
 [0.07831403613090515],
 [0.3403418958187103],
 [0.07411010563373566],
 [0.057453177869319916],
 [0.5007485747337341],
 [0.7347108721733093],
 [0.0351259745657444],
 [0.8076310753822327],
 [0.6784675717353821],
 [0.0256388820707798],
 [0.4964686334133148],
 [0.07315274327993393],
 [0.20537784695625305],
 [0.951126754283905],
 [0.16183605790138245],
 [0.5711489319801331],
 [0.1979484111070633],
 [0.01858885958790779],
 [0.9880933165550232],
 [0.6612061858177185],
 [0.65379399061203],
 [0.11654221266508102],
 [0.06658480316400528],
 [0.08110057562589645],
 [0.03126124292612076],
 [0.8335514664649963],
 [0.0429677776992321],
 [0.9457274079322815],
 [0.7907737493515015],
 [0.054549913853406906],
 [0.6332552433013916],
 [0.1378888636827469],
 [0.8629385828971863],
 [0.7262858748435974],
 [0.3645881712436676],
 [0.553859293460846],
 [0.29620689153671265],
 [0.9577587842941284],
 [0.18770785629749298],
 [0.007286079693585634],
 [0.04741509631276131],
 [0.43620288372039795],
 [0.427905410528183],
 [0.34483909606933594],
 [0.8190228939056396],
 [0.9245992302894592],
 [0.08371062576770782],
 [0.2866896986961365],
 [0.39578598737716675],
 [0.8308826088905334],
 [0.39985787868499756],
 [0.02931913174688816],
 [0.5240226984024048],
 [0.39897745847702026],
 [0.685192883014679],
 [0.9733071327209473],
 [0.16870012879371643],
 [0.9033158421516418],
 [0.238058403134346],
 [0.025741932913661003],
 [0.6002027988433838],
 [0.45174574851989746],
 [0.46918031573295593],
 [0.20830266177654266],
 [0.016774971038103104],
 [0.00190402299631387],
 [0.8320431113243103],
 [0.46636727452278137],
 [0.05280109494924545],
 [0.7092395424842834],
 [0.06209653615951538],
 [0.054404452443122864],
 [0.39507073163986206],
 [0.05205772817134857],
 [0.04658298194408417],
 [0.19981591403484344],
 [0.40403610467910767],
 [0.16651615500450134],
 [0.008095869794487953],
 [0.035671867430210114],
 [0.20345884561538696],
 [0.2887575626373291],
 [0.22580815851688385],
 [0.8063343167304993],
 [0.39247533679008484],
 [0.9288471341133118],
 [0.6366291046142578],
 [0.03657248243689537],
 [0.3507416844367981],
 [0.09722255170345306],
 [0.9167831540107727],
 [0.28550973534584045],
 [0.017023416236042976],
 [0.05225690081715584],
 [0.04995432868599892],
 [0.10652267932891846],
 [0.10248482972383499],
 [0.8680927753448486],
 [0.3431641161441803],
 [0.17715442180633545],
 [0.18319819867610931],
 [0.9205945730209351],
 [0.7917634844779968],
 [0.18591342866420746],
 [0.12438260763883591],
 [0.07709496468305588],
 [0.842976987361908],
 [0.8740721940994263],
 [0.32123956084251404],
 [0.5943989753723145],
 [0.13886915147304535],
 [0.39426538348197937],
 [0.8413786292076111],
 [0.2967860996723175],
 [0.09691046923398972],
 [0.18215778470039368],
 [0.22060951590538025],
 [0.04783965274691582],
 [0.1365022510290146],
 [0.50650554895401],
 [0.6665204763412476],
 [0.666924774646759],
 [0.6298685073852539],
 [0.07609567791223526],
 [0.20004215836524963],
 [0.11142848432064056],
 [0.016507431864738464],
 [0.7345330119132996],
 [0.7729105353355408],
 [0.8506646156311035],
 [0.9112941026687622],
 [0.09975975751876831],
 [0.389329195022583],
 [0.640694797039032],
 [0.21528621017932892],
 [0.786293089389801],
 [0.26672959327697754],
 [0.2634495794773102],
 [0.10430721938610077],
 [0.8866589069366455],
 [0.11439982801675797],
 [0.24976091086864471],
 [0.12722137570381165],
 [0.21120363473892212],
 [0.0747428834438324],
 [0.2494383603334427],
 [0.3099927604198456],
 [0.4118083119392395],
 [0.054714545607566833],
 [0.4295352101325989],
 [0.028291117399930954],
 [0.6832104325294495],
 [0.6486917734146118],
 [0.024850919842720032],
 [0.536964476108551],
 [0.12495162338018417],
 [0.6247480511665344],
 [0.0814453661441803],
 [0.8539680242538452],
 [0.9415338635444641],
 [0.05307791754603386],
 [0.04162510111927986],
 [0.6183695197105408],
 [0.1960422396659851],
 [0.49873316287994385],
 [0.7836748957633972],
 [0.01806178316473961],
 [0.8390730023384094],
 [0.8515245914459229],
 [0.14035001397132874],
 [0.8641748428344727],
 [0.1093934029340744],
 [0.9222052693367004],
 [0.28663724660873413],
 [0.2035641223192215],
 [0.6804813742637634],
 [0.46382492780685425],
 [0.06745237112045288],
 [0.07057421654462814],
 [0.09349537640810013],
 [0.6911673545837402],
 [0.028040269389748573],
 [0.06127511337399483],
 [0.7482002377510071],
 [0.6357601881027222],
 [0.08359795808792114],
 [0.4209599196910858],
 [0.021648231893777847],
 [0.19390416145324707],
 [0.09071586281061172],
 [0.36707761883735657],
 [0.9419416189193726],
 [0.08844161778688431],
 [0.5839523673057556],
 [0.2419928014278412],
 [0.18418879806995392],
 [0.6247172355651855],
 [0.40591543912887573],
 [0.7374206781387329],
 [0.6408859491348267],
 [0.39042988419532776],
 [0.7253220081329346],
 [0.77967369556427],
 [0.020985791459679604],
 [0.24697190523147583],
 [0.30527442693710327],
 [0.015121116302907467],
 [0.10830584168434143],
 [0.09076738357543945],
 [0.7124252319335938],
 [0.008188788779079914],
 [0.7370963096618652],
 [0.47186726331710815],
 [0.8325502276420593],
 [0.1639977991580963],
 [0.6808363199234009],
 [0.08638929575681686],
 [0.43924546241760254],
 [0.5724360346794128],
 [0.3745265007019043],
 [0.31237873435020447],
 [0.8127306699752808],
 [0.1844796985387802],
 [0.051528435200452805],
 [0.12513621151447296],
 [0.3915722370147705],
 [0.13156381249427795],
 [0.29296302795410156],
 [0.4155104458332062],
 [0.7188096642494202],
 [0.6826369166374207],
 [0.01628640480339527],
 [0.3388146758079529],
 [0.4654625952243805],
 [0.3567260801792145],
 [0.07005999982357025],
 [0.032955292612314224],
 [0.2926146984100342],

In [143]:
import math
def AMS(s, b):
    """ Approximate Median Significance defined as:
        AMS = sqrt(
                2 { (s + b + b_r) log[1 + (s/(b+b_r))] - s}
              )        
    where b_r = 10, b = background, s = signal, log is natural logarithm """
    
    br = 10.0
    radicand = 2 *( (s+b+br) * math.log (1.0 + s/(b+br)) -s)
    if radicand < 0:
        print('radicand is negative. Exiting')
        exit()
    else:
        return math.sqrt(radicand)

In [144]:
# Training performance
y_gold = orig_train_data['Label']
y_weight = orig_train_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[0] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TRAINING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TRAINING: (S,B) = (592.605,87199.414), AMS=2.004, Unweighted Precision = 0.577

In [145]:
y_pred = best_model(torch.tensor(normed_public_test_data.values, dtype=torch.float)).tolist()

In [146]:
y_gold = orig_public_test_data['Label']
y_weight = orig_public_test_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[0] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"VALID: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

VALID: (S,B) = (436.155,51380.692), AMS=1.921, Unweighted Precision = 0.606

In [147]:
y_pred = best_model(torch.tensor(normed_private_test_data.values, dtype=torch.float)).tolist()

In [148]:
y_gold = orig_private_test_data['Label']
y_weight = orig_private_test_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[0] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TEST: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TEST: (S,B) = (432.595,50731.178), AMS=1.918, Unweighted Precision = 0.613

In [ ]:
# stop train when val loss not decreasing three times in a row
# vary dropout
# deeper nets
# different activations

In [150]:
best_model.info()

AttributeError: 'Feedforward' object has no attribute 'info'