In [2]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.0.4-cp39-none-manylinux1_x86_64.whl (76.2 MB)
     |████████████████████████████████| 76.2 MB 34.0 MB/s
Requirement already satisfied: numpy>=1.16.0 in /opt/conda/lib/python3.9/site-packages (from catboost) (1.22.1)
Requirement already satisfied: plotly in /opt/conda/lib/python3.9/site-packages (from catboost) (4.14.3)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.9/site-packages (from catboost) (3.5.1)
Requirement already satisfied: six in /opt/conda/lib/python3.9/site-packages (from catboost) (1.16.0)
Requirement already satisfied: pandas>=0.24.0 in /opt/conda/lib/python3.9/site-packages (from catboost) (1.4.0)
Requirement already satisfied: scipy in /opt/conda/lib/python3.9/site-packages (from catboost) (1.7.3)
Requirement already satisfied: graphviz in /opt/conda/lib/python3.9/site-packages (from catboost) (0.19.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.9/site-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.9/site-packages (from pandas>=0.24.0->catboost) (2021.3)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (9.0.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (4.29.0)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (3.0.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (21.3)
Requirement already satisfied: retrying>=1.3.3 in /opt/conda/lib/python3.9/site-packages (from plotly->catboost) (1.3.3)
Installing collected packages: catboost
Successfully installed catboost-1.0.4

In [19]:
## import the libraries needed
import pandas as pd
import numpy as np


# Here we import our dataset from the CatBoost dataset library
from catboost.datasets import titanic

In [20]:
## The titanic dataset is made up of the train and test set, so we have to separate the data
titanic_train, titanic_test = titanic()

## Here we create a list to sort the columns so that the "Survived" column comes last
## This is because "Survived" is the target
column_sort = [ 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
'Fare', 'Cabin', 'Embarked','Survived']

## Now we apply the sorted columns to the train data
train = titanic_train[column_sort]
train.set_index('Pclass') ## Not necessary just to get of the default index

test = titanic_test
train.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [12]:
## Remember the target column - "Survived" - we identified in the cell above,
## it is missing in the test set
## To solve this problem, we would create a column and fill it with dummy values,
## let's say '2' so it is not dormant and we can merge the DataFrame later
test['Survived'] = 2  ## The numpy background of pandas allows this to work
test.sample(5) ## shows five random rows in the dataset

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
254,1146,3,"Wenzel, Mr. Linhart",male,32.5,0,0,345775,9.5000,NaN,S,2
208,1100,1,"Rosenbaum, Miss. Edith Louise",female,33.0,0,0,PC 17613,27.7208,A11,C,2
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S,2
91,983,3,"Pedersen, Mr. Olaf",male,NaN,0,0,345498,7.7750,NaN,S,2
293,1185,1,"Dodge, Dr. Washington",male,53.0,1,1,33638,81.8583,A34,S,2

In [21]:
## We would combine the train and test set into one DataFrame,
## so we do not have to repeat the same process for the two sets
df = pd.concat([train,test],ignore_index = False)

## Some features (such as Name, and Age) are irrelevant so we delete them
df = df.drop(['Name', 'Age'], axis=1)

## The data is not clean so we check all the columns for missing values
df.isnull().sum(axis=0)

Pclass            0
Sex               0
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
Survived        418
PassengerId     891
dtype: int64

In [22]:
## "Fare", "Cabin", "Embarked", and "PassengerId" have missing values, we have to fix this
df['Embarked'] = df['Embarked'].fillna('S') ## The missing values in Embarked is filled with "S" (for Southampton), the most common value observed in that column
df['Cabin'] = df['Cabin'].fillna('Undefined')
df.fillna(-999, inplace=True)

## Now that the data looks good, we have to separate the train from the test set
train = df[df.Survived != 2]

test = df[df.Survived == 2]
test = test.drop(['Survived'], axis=1) ## drop the placeholder we created earlier in the test set

## Pop out the training features from the target variable
target = train.pop('Survived')
target.head()

0    0.0
1    1.0
2    1.0
3    1.0
4    0.0
Name: Survived, dtype: float64

In [23]:
## Let's ensure the model is trained and fit well
cat_features_index = np.where(train.dtypes != float)[0]

## Split the data into a train and test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(train, target,
train_size=0.85, random_state=1234)

In [27]:
cat_features_index
train.head()

,Pclass,Sex,SibSp,Parch,Ticket,Fare,Cabin,Embarked,PassengerId
0,3,male,1,0,A/5 21171,7.2500,Undefined,S,-999.0
1,1,female,1,0,PC 17599,71.2833,C85,C,-999.0
2,3,female,0,0,STON/O2. 3101282,7.9250,Undefined,S,-999.0
3,1,female,1,0,113803,53.1000,C123,S,-999.0
4,3,male,0,0,373450,8.0500,Undefined,S,-999.0

In [9]:
## Import the CatBoostClassifier to fit the model and run a prediction
from catboost import CatBoostClassifier
model = CatBoostClassifier(
    custom_loss=['Accuracy'],
    random_seed=42)

## Set the metric for evaluation
model = CatBoostClassifier(eval_metric='Accuracy',
use_best_model=True,  random_seed=42)

model.fit(X_train, y_train, cat_features=cat_features_index,
eval_set=(X_test, y_test))


from catboost import cv
from sklearn.metrics import accuracy_score

print('the test accuracy is :{:.6f}'.format(accuracy_score(
y_test, model.predict(X_test))))

Learning rate set to 0.029583
0:	learn: 0.8031704	test: 0.8059701	best: 0.8059701 (0)	total: 53.1ms	remaining: 53s
1:	learn: 0.8137384	test: 0.8059701	best: 0.8059701 (0)	total: 56.8ms	remaining: 28.3s
2:	learn: 0.8150594	test: 0.8059701	best: 0.8059701 (0)	total: 58.2ms	remaining: 19.3s
3:	learn: 0.8177015	test: 0.8059701	best: 0.8059701 (0)	total: 61ms	remaining: 15.2s
4:	learn: 0.8163804	test: 0.8059701	best: 0.8059701 (0)	total: 63.3ms	remaining: 12.6s
5:	learn: 0.8163804	test: 0.8059701	best: 0.8059701 (0)	total: 64.2ms	remaining: 10.6s
6:	learn: 0.8150594	test: 0.8059701	best: 0.8059701 (0)	total: 66.4ms	remaining: 9.42s
7:	learn: 0.8163804	test: 0.8059701	best: 0.8059701 (0)	total: 67.5ms	remaining: 8.37s
8:	learn: 0.8110964	test: 0.8059701	best: 0.8059701 (0)	total: 71.3ms	remaining: 7.86s
9:	learn: 0.8137384	test: 0.8059701	best: 0.8059701 (0)	total: 73.5ms	remaining: 7.28s
10:	learn: 0.8150594	test: 0.8059701	best: 0.8059701 (0)	total: 75.5ms	remaining: 6.79s
11:	learn: 0.8163804	test: 0.8059701	best: 0.8059701 (0)	total: 77.4ms	remaining: 6.37s
12:	learn: 0.8190225	test: 0.8059701	best: 0.8059701 (0)	total: 79.6ms	remaining: 6.04s
13:	learn: 0.8177015	test: 0.8059701	best: 0.8059701 (0)	total: 80.7ms	remaining: 5.68s
14:	learn: 0.8177015	test: 0.8059701	best: 0.8059701 (0)	total: 82.7ms	remaining: 5.43s
15:	learn: 0.8177015	test: 0.8059701	best: 0.8059701 (0)	total: 84.6ms	remaining: 5.21s
16:	learn: 0.8124174	test: 0.8059701	best: 0.8059701 (0)	total: 86.6ms	remaining: 5.01s
17:	learn: 0.8163804	test: 0.8059701	best: 0.8059701 (0)	total: 88.6ms	remaining: 4.83s
18:	learn: 0.8177015	test: 0.8059701	best: 0.8059701 (0)	total: 90.5ms	remaining: 4.67s
19:	learn: 0.8177015	test: 0.8059701	best: 0.8059701 (0)	total: 92.3ms	remaining: 4.52s
20:	learn: 0.8163804	test: 0.8059701	best: 0.8059701 (0)	total: 94.4ms	remaining: 4.4s
21:	learn: 0.8177015	test: 0.8059701	best: 0.8059701 (0)	total: 96ms	remaining: 4.27s
22:	learn: 0.8177015	test: 0.8059701	best: 0.8059701 (0)	total: 97.9ms	remaining: 4.16s
23:	learn: 0.8203435	test: 0.8059701	best: 0.8059701 (0)	total: 99.2ms	remaining: 4.03s
24:	learn: 0.8203435	test: 0.8059701	best: 0.8059701 (0)	total: 100ms	remaining: 3.91s
25:	learn: 0.8229855	test: 0.8059701	best: 0.8059701 (0)	total: 102ms	remaining: 3.84s
26:	learn: 0.8190225	test: 0.8059701	best: 0.8059701 (0)	total: 104ms	remaining: 3.76s
27:	learn: 0.8203435	test: 0.8059701	best: 0.8059701 (0)	total: 106ms	remaining: 3.68s
28:	learn: 0.8203435	test: 0.8059701	best: 0.8059701 (0)	total: 108ms	remaining: 3.63s
29:	learn: 0.8216645	test: 0.8059701	best: 0.8059701 (0)	total: 110ms	remaining: 3.56s
30:	learn: 0.8216645	test: 0.8059701	best: 0.8059701 (0)	total: 112ms	remaining: 3.5s
31:	learn: 0.8203435	test: 0.8059701	best: 0.8059701 (0)	total: 115ms	remaining: 3.47s
32:	learn: 0.8216645	test: 0.8059701	best: 0.8059701 (0)	total: 117ms	remaining: 3.42s
33:	learn: 0.8216645	test: 0.8059701	best: 0.8059701 (0)	total: 118ms	remaining: 3.35s
34:	learn: 0.8229855	test: 0.8059701	best: 0.8059701 (0)	total: 120ms	remaining: 3.31s
35:	learn: 0.8216645	test: 0.8059701	best: 0.8059701 (0)	total: 122ms	remaining: 3.27s
36:	learn: 0.8216645	test: 0.8059701	best: 0.8059701 (0)	total: 124ms	remaining: 3.22s
37:	learn: 0.8229855	test: 0.8059701	best: 0.8059701 (0)	total: 126ms	remaining: 3.19s
38:	learn: 0.8229855	test: 0.8059701	best: 0.8059701 (0)	total: 127ms	remaining: 3.13s
39:	learn: 0.8243065	test: 0.8059701	best: 0.8059701 (0)	total: 129ms	remaining: 3.09s
40:	learn: 0.8243065	test: 0.8059701	best: 0.8059701 (0)	total: 131ms	remaining: 3.05s
41:	learn: 0.8256275	test: 0.8059701	best: 0.8059701 (0)	total: 133ms	remaining: 3.02s
42:	learn: 0.8256275	test: 0.8059701	best: 0.8059701 (0)	total: 134ms	remaining: 2.99s
43:	learn: 0.8256275	test: 0.8059701	best: 0.8059701 (0)	total: 135ms	remaining: 2.94s
44:	learn: 0.8256275	test: 0.8059701	best: 0.8059701 (0)	total: 137ms	remaining: 2.91s
45:	learn: 0.8282695	test: 0.8059701	best: 0.8059701 (0)	total: 139ms	remaining: 2.88s
46:	learn: 0.8282695	test: 0.8059701	best: 0.8059701 (0)	total: 140ms	remaining: 2.85s
47:	learn: 0.8282695	test: 0.8059701	best: 0.8059701 (0)	total: 142ms	remaining: 2.82s
48:	learn: 0.8295905	test: 0.8059701	best: 0.8059701 (0)	total: 143ms	remaining: 2.77s
49:	learn: 0.8295905	test: 0.8059701	best: 0.8059701 (0)	total: 145ms	remaining: 2.75s
50:	learn: 0.8309115	test: 0.8059701	best: 0.8059701 (0)	total: 146ms	remaining: 2.72s
51:	learn: 0.8309115	test: 0.8059701	best: 0.8059701 (0)	total: 148ms	remaining: 2.7s
52:	learn: 0.8322325	test: 0.8059701	best: 0.8059701 (0)	total: 150ms	remaining: 2.68s
53:	learn: 0.8295905	test: 0.8059701	best: 0.8059701 (0)	total: 151ms	remaining: 2.65s
54:	learn: 0.8335535	test: 0.8059701	best: 0.8059701 (0)	total: 152ms	remaining: 2.62s
55:	learn: 0.8335535	test: 0.8059701	best: 0.8059701 (0)	total: 154ms	remaining: 2.6s
56:	learn: 0.8335535	test: 0.8134328	best: 0.8134328 (56)	total: 156ms	remaining: 2.58s
57:	learn: 0.8335535	test: 0.8134328	best: 0.8134328 (56)	total: 157ms	remaining: 2.55s
58:	learn: 0.8361955	test: 0.8134328	best: 0.8134328 (56)	total: 159ms	remaining: 2.54s
59:	learn: 0.8361955	test: 0.8134328	best: 0.8134328 (56)	total: 160ms	remaining: 2.5s
60:	learn: 0.8348745	test: 0.8134328	best: 0.8134328 (56)	total: 162ms	remaining: 2.49s
61:	learn: 0.8361955	test: 0.8134328	best: 0.8134328 (56)	total: 164ms	remaining: 2.48s
62:	learn: 0.8361955	test: 0.8134328	best: 0.8134328 (56)	total: 165ms	remaining: 2.46s
63:	learn: 0.8361955	test: 0.8134328	best: 0.8134328 (56)	total: 167ms	remaining: 2.44s
64:	learn: 0.8361955	test: 0.8134328	best: 0.8134328 (56)	total: 169ms	remaining: 2.43s
65:	learn: 0.8375165	test: 0.8134328	best: 0.8134328 (56)	total: 170ms	remaining: 2.41s
66:	learn: 0.8375165	test: 0.8134328	best: 0.8134328 (56)	total: 172ms	remaining: 2.4s
67:	learn: 0.8375165	test: 0.8134328	best: 0.8134328 (56)	total: 174ms	remaining: 2.38s
68:	learn: 0.8375165	test: 0.8134328	best: 0.8134328 (56)	total: 175ms	remaining: 2.36s
69:	learn: 0.8375165	test: 0.8134328	best: 0.8134328 (56)	total: 177ms	remaining: 2.36s
70:	learn: 0.8375165	test: 0.8134328	best: 0.8134328 (56)	total: 179ms	remaining: 2.35s
71:	learn: 0.8375165	test: 0.8134328	best: 0.8134328 (56)	total: 181ms	remaining: 2.34s
72:	learn: 0.8375165	test: 0.8134328	best: 0.8134328 (56)	total: 183ms	remaining: 2.33s
73:	learn: 0.8375165	test: 0.8134328	best: 0.8134328 (56)	total: 185ms	remaining: 2.32s
74:	learn: 0.8375165	test: 0.8134328	best: 0.8134328 (56)	total: 186ms	remaining: 2.29s
75:	learn: 0.8375165	test: 0.8134328	best: 0.8134328 (56)	total: 188ms	remaining: 2.29s
76:	learn: 0.8388375	test: 0.8134328	best: 0.8134328 (56)	total: 191ms	remaining: 2.28s
77:	learn: 0.8388375	test: 0.8134328	best: 0.8134328 (56)	total: 192ms	remaining: 2.27s
78:	learn: 0.8388375	test: 0.8134328	best: 0.8134328 (56)	total: 194ms	remaining: 2.27s
79:	learn: 0.8388375	test: 0.8134328	best: 0.8134328 (56)	total: 196ms	remaining: 2.26s
80:	learn: 0.8388375	test: 0.8134328	best: 0.8134328 (56)	total: 197ms	remaining: 2.24s
81:	learn: 0.8388375	test: 0.8134328	best: 0.8134328 (56)	total: 199ms	remaining: 2.23s
82:	learn: 0.8388375	test: 0.8134328	best: 0.8134328 (56)	total: 201ms	remaining: 2.22s
83:	learn: 0.8388375	test: 0.8134328	best: 0.8134328 (56)	total: 203ms	remaining: 2.21s
84:	learn: 0.8388375	test: 0.8134328	best: 0.8134328 (56)	total: 204ms	remaining: 2.2s
85:	learn: 0.8388375	test: 0.8134328	best: 0.8134328 (56)	total: 206ms	remaining: 2.19s
86:	learn: 0.8480845	test: 0.8059701	best: 0.8134328 (56)	total: 208ms	remaining: 2.18s
87:	learn: 0.8494055	test: 0.8059701	best: 0.8134328 (56)	total: 210ms	remaining: 2.17s
88:	learn: 0.8494055	test: 0.8059701	best: 0.8134328 (56)	total: 212ms	remaining: 2.17s
89:	learn: 0.8494055	test: 0.8134328	best: 0.8134328 (56)	total: 213ms	remaining: 2.16s
90:	learn: 0.8507266	test: 0.8059701	best: 0.8134328 (56)	total: 215ms	remaining: 2.15s
91:	learn: 0.8507266	test: 0.8059701	best: 0.8134328 (56)	total: 217ms	remaining: 2.15s
92:	learn: 0.8494055	test: 0.8059701	best: 0.8134328 (56)	total: 219ms	remaining: 2.14s
93:	learn: 0.8507266	test: 0.8059701	best: 0.8134328 (56)	total: 221ms	remaining: 2.13s
94:	learn: 0.8494055	test: 0.8059701	best: 0.8134328 (56)	total: 222ms	remaining: 2.11s
95:	learn: 0.8520476	test: 0.8059701	best: 0.8134328 (56)	total: 224ms	remaining: 2.11s
96:	learn: 0.8520476	test: 0.8059701	best: 0.8134328 (56)	total: 225ms	remaining: 2.1s
97:	learn: 0.8507266	test: 0.8059701	best: 0.8134328 (56)	total: 226ms	remaining: 2.08s
98:	learn: 0.8507266	test: 0.8059701	best: 0.8134328 (56)	total: 228ms	remaining: 2.08s
99:	learn: 0.8507266	test: 0.8059701	best: 0.8134328 (56)	total: 230ms	remaining: 2.07s
100:	learn: 0.8494055	test: 0.8059701	best: 0.8134328 (56)	total: 232ms	remaining: 2.07s
101:	learn: 0.8520476	test: 0.8059701	best: 0.8134328 (56)	total: 234ms	remaining: 2.06s
102:	learn: 0.8520476	test: 0.8059701	best: 0.8134328 (56)	total: 236ms	remaining: 2.05s
103:	learn: 0.8507266	test: 0.8059701	best: 0.8134328 (56)	total: 237ms	remaining: 2.04s
104:	learn: 0.8520476	test: 0.8059701	best: 0.8134328 (56)	total: 239ms	remaining: 2.04s
105:	learn: 0.8520476	test: 0.8059701	best: 0.8134328 (56)	total: 241ms	remaining: 2.03s
106:	learn: 0.8520476	test: 0.8059701	best: 0.8134328 (56)	total: 241ms	remaining: 2.02s
107:	learn: 0.8520476	test: 0.8059701	best: 0.8134328 (56)	total: 244ms	remaining: 2.01s
108:	learn: 0.8520476	test: 0.8059701	best: 0.8134328 (56)	total: 245ms	remaining: 2s
109:	learn: 0.8546896	test: 0.8059701	best: 0.8134328 (56)	total: 247ms	remaining: 2s
110:	learn: 0.8533686	test: 0.8059701	best: 0.8134328 (56)	total: 249ms	remaining: 1.99s
111:	learn: 0.8560106	test: 0.8059701	best: 0.8134328 (56)	total: 251ms	remaining: 1.99s
112:	learn: 0.8560106	test: 0.8059701	best: 0.8134328 (56)	total: 252ms	remaining: 1.97s
113:	learn: 0.8573316	test: 0.8059701	best: 0.8134328 (56)	total: 253ms	remaining: 1.97s
114:	learn: 0.8560106	test: 0.8059701	best: 0.8134328 (56)	total: 255ms	remaining: 1.96s
115:	learn: 0.8560106	test: 0.8059701	best: 0.8134328 (56)	total: 257ms	remaining: 1.96s
116:	learn: 0.8560106	test: 0.8059701	best: 0.8134328 (56)	total: 258ms	remaining: 1.95s
117:	learn: 0.8560106	test: 0.8059701	best: 0.8134328 (56)	total: 260ms	remaining: 1.95s
118:	learn: 0.8560106	test: 0.8059701	best: 0.8134328 (56)	total: 262ms	remaining: 1.94s
119:	learn: 0.8573316	test: 0.8059701	best: 0.8134328 (56)	total: 264ms	remaining: 1.94s
120:	learn: 0.8573316	test: 0.8059701	best: 0.8134328 (56)	total: 266ms	remaining: 1.93s
121:	learn: 0.8599736	test: 0.8059701	best: 0.8134328 (56)	total: 268ms	remaining: 1.93s
122:	learn: 0.8573316	test: 0.8059701	best: 0.8134328 (56)	total: 269ms	remaining: 1.92s
123:	learn: 0.8599736	test: 0.8059701	best: 0.8134328 (56)	total: 270ms	remaining: 1.91s
124:	learn: 0.8573316	test: 0.8059701	best: 0.8134328 (56)	total: 272ms	remaining: 1.9s
125:	learn: 0.8599736	test: 0.8059701	best: 0.8134328 (56)	total: 273ms	remaining: 1.9s
126:	learn: 0.8586526	test: 0.8059701	best: 0.8134328 (56)	total: 275ms	remaining: 1.89s
127:	learn: 0.8639366	test: 0.8059701	best: 0.8134328 (56)	total: 276ms	remaining: 1.88s
128:	learn: 0.8639366	test: 0.8059701	best: 0.8134328 (56)	total: 278ms	remaining: 1.87s
129:	learn: 0.8639366	test: 0.8059701	best: 0.8134328 (56)	total: 279ms	remaining: 1.87s
130:	learn: 0.8639366	test: 0.8059701	best: 0.8134328 (56)	total: 292ms	remaining: 1.93s
131:	learn: 0.8639366	test: 0.8059701	best: 0.8134328 (56)	total: 293ms	remaining: 1.93s
132:	learn: 0.8639366	test: 0.8059701	best: 0.8134328 (56)	total: 295ms	remaining: 1.93s
133:	learn: 0.8639366	test: 0.8059701	best: 0.8134328 (56)	total: 297ms	remaining: 1.92s
134:	learn: 0.8652576	test: 0.8134328	best: 0.8134328 (56)	total: 299ms	remaining: 1.91s
135:	learn: 0.8652576	test: 0.8059701	best: 0.8134328 (56)	total: 301ms	remaining: 1.91s
136:	learn: 0.8639366	test: 0.8134328	best: 0.8134328 (56)	total: 304ms	remaining: 1.91s
137:	learn: 0.8652576	test: 0.8134328	best: 0.8134328 (56)	total: 306ms	remaining: 1.91s
138:	learn: 0.8652576	test: 0.8134328	best: 0.8134328 (56)	total: 307ms	remaining: 1.9s
139:	learn: 0.8639366	test: 0.8059701	best: 0.8134328 (56)	total: 309ms	remaining: 1.9s
140:	learn: 0.8652576	test: 0.8059701	best: 0.8134328 (56)	total: 311ms	remaining: 1.89s
141:	learn: 0.8639366	test: 0.8059701	best: 0.8134328 (56)	total: 313ms	remaining: 1.89s
142:	learn: 0.8652576	test: 0.8059701	best: 0.8134328 (56)	total: 314ms	remaining: 1.88s
143:	learn: 0.8639366	test: 0.8059701	best: 0.8134328 (56)	total: 316ms	remaining: 1.88s
144:	learn: 0.8665786	test: 0.8059701	best: 0.8134328 (56)	total: 318ms	remaining: 1.88s
145:	learn: 0.8678996	test: 0.8059701	best: 0.8134328 (56)	total: 320ms	remaining: 1.87s
146:	learn: 0.8705416	test: 0.7985075	best: 0.8134328 (56)	total: 322ms	remaining: 1.86s
147:	learn: 0.8705416	test: 0.7985075	best: 0.8134328 (56)	total: 323ms	remaining: 1.86s
148:	learn: 0.8692206	test: 0.7985075	best: 0.8134328 (56)	total: 325ms	remaining: 1.85s
149:	learn: 0.8692206	test: 0.7985075	best: 0.8134328 (56)	total: 327ms	remaining: 1.85s
150:	learn: 0.8692206	test: 0.7985075	best: 0.8134328 (56)	total: 329ms	remaining: 1.85s
151:	learn: 0.8692206	test: 0.7985075	best: 0.8134328 (56)	total: 330ms	remaining: 1.84s
152:	learn: 0.8678996	test: 0.7985075	best: 0.8134328 (56)	total: 331ms	remaining: 1.83s
153:	learn: 0.8705416	test: 0.7985075	best: 0.8134328 (56)	total: 333ms	remaining: 1.83s
154:	learn: 0.8678996	test: 0.7985075	best: 0.8134328 (56)	total: 335ms	remaining: 1.83s
155:	learn: 0.8692206	test: 0.7985075	best: 0.8134328 (56)	total: 336ms	remaining: 1.82s
156:	learn: 0.8692206	test: 0.7985075	best: 0.8134328 (56)	total: 338ms	remaining: 1.81s
157:	learn: 0.8678996	test: 0.7985075	best: 0.8134328 (56)	total: 340ms	remaining: 1.81s
158:	learn: 0.8678996	test: 0.7985075	best: 0.8134328 (56)	total: 341ms	remaining: 1.8s
159:	learn: 0.8678996	test: 0.8059701	best: 0.8134328 (56)	total: 342ms	remaining: 1.8s
160:	learn: 0.8678996	test: 0.8059701	best: 0.8134328 (56)	total: 344ms	remaining: 1.79s
161:	learn: 0.8665786	test: 0.8059701	best: 0.8134328 (56)	total: 345ms	remaining: 1.78s
162:	learn: 0.8678996	test: 0.8059701	best: 0.8134328 (56)	total: 347ms	remaining: 1.78s
163:	learn: 0.8678996	test: 0.8059701	best: 0.8134328 (56)	total: 348ms	remaining: 1.78s
164:	learn: 0.8678996	test: 0.8059701	best: 0.8134328 (56)	total: 350ms	remaining: 1.77s
165:	learn: 0.8678996	test: 0.8059701	best: 0.8134328 (56)	total: 352ms	remaining: 1.77s
166:	learn: 0.8678996	test: 0.8059701	best: 0.8134328 (56)	total: 353ms	remaining: 1.76s
167:	learn: 0.8678996	test: 0.8059701	best: 0.8134328 (56)	total: 355ms	remaining: 1.76s
168:	learn: 0.8678996	test: 0.8059701	best: 0.8134328 (56)	total: 356ms	remaining: 1.75s
169:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 358ms	remaining: 1.75s
170:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 359ms	remaining: 1.74s
171:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 361ms	remaining: 1.74s
172:	learn: 0.8678996	test: 0.8059701	best: 0.8134328 (56)	total: 363ms	remaining: 1.73s
173:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 364ms	remaining: 1.73s
174:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 366ms	remaining: 1.72s
175:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 367ms	remaining: 1.72s
176:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 367ms	remaining: 1.71s
177:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 369ms	remaining: 1.7s
178:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 371ms	remaining: 1.7s
179:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 373ms	remaining: 1.7s
180:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 375ms	remaining: 1.69s
181:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 376ms	remaining: 1.69s
182:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 378ms	remaining: 1.69s
183:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 380ms	remaining: 1.68s
184:	learn: 0.8692206	test: 0.8059701	best: 0.8134328 (56)	total: 381ms	remaining: 1.68s
185:	learn: 0.8705416	test: 0.8059701	best: 0.8134328 (56)	total: 383ms	remaining: 1.68s
186:	learn: 0.8705416	test: 0.8059701	best: 0.8134328 (56)	total: 385ms	remaining: 1.68s
187:	learn: 0.8705416	test: 0.8059701	best: 0.8134328 (56)	total: 387ms	remaining: 1.67s
188:	learn: 0.8705416	test: 0.8059701	best: 0.8134328 (56)	total: 388ms	remaining: 1.67s
189:	learn: 0.8705416	test: 0.8059701	best: 0.8134328 (56)	total: 390ms	remaining: 1.66s
190:	learn: 0.8705416	test: 0.8059701	best: 0.8134328 (56)	total: 392ms	remaining: 1.66s
191:	learn: 0.8705416	test: 0.8059701	best: 0.8134328 (56)	total: 394ms	remaining: 1.66s
192:	learn: 0.8705416	test: 0.8059701	best: 0.8134328 (56)	total: 395ms	remaining: 1.65s
193:	learn: 0.8705416	test: 0.8059701	best: 0.8134328 (56)	total: 397ms	remaining: 1.65s
194:	learn: 0.8718626	test: 0.8059701	best: 0.8134328 (56)	total: 399ms	remaining: 1.65s
195:	learn: 0.8718626	test: 0.8059701	best: 0.8134328 (56)	total: 401ms	remaining: 1.65s
196:	learn: 0.8718626	test: 0.8059701	best: 0.8134328 (56)	total: 403ms	remaining: 1.64s
197:	learn: 0.8718626	test: 0.8059701	best: 0.8134328 (56)	total: 405ms	remaining: 1.64s
198:	learn: 0.8718626	test: 0.8059701	best: 0.8134328 (56)	total: 407ms	remaining: 1.64s
199:	learn: 0.8718626	test: 0.8059701	best: 0.8134328 (56)	total: 409ms	remaining: 1.64s
200:	learn: 0.8731836	test: 0.8059701	best: 0.8134328 (56)	total: 411ms	remaining: 1.64s
201:	learn: 0.8731836	test: 0.8059701	best: 0.8134328 (56)	total: 414ms	remaining: 1.63s
202:	learn: 0.8731836	test: 0.8059701	best: 0.8134328 (56)	total: 415ms	remaining: 1.63s
203:	learn: 0.8745046	test: 0.8059701	best: 0.8134328 (56)	total: 417ms	remaining: 1.63s
204:	learn: 0.8745046	test: 0.8059701	best: 0.8134328 (56)	total: 419ms	remaining: 1.62s
205:	learn: 0.8745046	test: 0.8059701	best: 0.8134328 (56)	total: 421ms	remaining: 1.62s
206:	learn: 0.8745046	test: 0.8059701	best: 0.8134328 (56)	total: 422ms	remaining: 1.62s
207:	learn: 0.8731836	test: 0.8059701	best: 0.8134328 (56)	total: 424ms	remaining: 1.61s
208:	learn: 0.8731836	test: 0.8059701	best: 0.8134328 (56)	total: 426ms	remaining: 1.61s
209:	learn: 0.8758256	test: 0.8059701	best: 0.8134328 (56)	total: 428ms	remaining: 1.61s
210:	learn: 0.8758256	test: 0.8059701	best: 0.8134328 (56)	total: 429ms	remaining: 1.6s
211:	learn: 0.8758256	test: 0.8059701	best: 0.8134328 (56)	total: 431ms	remaining: 1.6s
212:	learn: 0.8758256	test: 0.8059701	best: 0.8134328 (56)	total: 433ms	remaining: 1.6s
213:	learn: 0.8758256	test: 0.8059701	best: 0.8134328 (56)	total: 435ms	remaining: 1.6s
214:	learn: 0.8771466	test: 0.8059701	best: 0.8134328 (56)	total: 437ms	remaining: 1.6s
215:	learn: 0.8771466	test: 0.8059701	best: 0.8134328 (56)	total: 439ms	remaining: 1.59s
216:	learn: 0.8771466	test: 0.8059701	best: 0.8134328 (56)	total: 441ms	remaining: 1.59s
217:	learn: 0.8771466	test: 0.8059701	best: 0.8134328 (56)	total: 443ms	remaining: 1.59s
218:	learn: 0.8771466	test: 0.8059701	best: 0.8134328 (56)	total: 445ms	remaining: 1.58s
219:	learn: 0.8771466	test: 0.8059701	best: 0.8134328 (56)	total: 446ms	remaining: 1.58s
220:	learn: 0.8771466	test: 0.8059701	best: 0.8134328 (56)	total: 448ms	remaining: 1.58s
221:	learn: 0.8771466	test: 0.8059701	best: 0.8134328 (56)	total: 449ms	remaining: 1.57s
222:	learn: 0.8771466	test: 0.7985075	best: 0.8134328 (56)	total: 451ms	remaining: 1.57s
223:	learn: 0.8771466	test: 0.8059701	best: 0.8134328 (56)	total: 453ms	remaining: 1.57s
224:	learn: 0.8771466	test: 0.7985075	best: 0.8134328 (56)	total: 455ms	remaining: 1.57s
225:	learn: 0.8771466	test: 0.7985075	best: 0.8134328 (56)	total: 457ms	remaining: 1.57s

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier(max_depth=2, random_state=0)